### PR TITLE
Clean up Makefile.am

### PR DESCRIPTION
**Pull request by thac0**
Ensure that dependency tracking is enabled for all headers and config
files. Add them to SOURCES for tracking and prevent them from being
installed on target system by autotools. Because we are doing this,
autotools documentation recommends we not add headers to a 'noinst'
target any longer.

Move the README.md content into the README file, and add a symlink to
README.md for GitHub's sake. As a side-effect, README (and all its
content) will now be included in the 'make dist' target.

Remove COPYING from EXTRA_DIST, as that is one of the files
automatically picked up by autotools.

Signed-off-by: Joe Konno <joe.konno@intel.com>

### CODE REVIEW

**Review by phmccarty — COMMENTED** [review]
With these changes, I created a dist tarball with `./configure; make dist`. Then I tried a build using the dist tarball contents with `./configure; make` and encountered this error:

```
make[1]: *** No rule to make target 'clr-power-tweaks.conf', needed by 'generated.c'.  Stop.
```

**Comment by thac0** [comment]
Thanks @phmccarty . Grumble grumble autotools grumble grumble. I'll fix and re-submit.

> With these changes, I created a dist tarball with `./configure; make dist`. Then I tried a build using the dist tarball contents with `./configure; make` and encountered this error:
> 
> ```
> make[1]: *** No rule to make target 'clr-power-tweaks.conf', needed by 'generated.c'.  Stop.
> ```

**Comment by thac0** [comment]
Unfortunately for us, clr-power-tweaks has been failing `make distcheck` for a looong time. So, I'll need to dig deeper into a greater build system bug here.

**Comment by thac0** [comment]
@phmccarty @bryteise - Rebase complete. It passes `distcheck` on my end.

**Review by phmccarty — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
